# yaml-language-server: $schema=https://raw.githubusercontent.com/jesseduffield/lazygit/master/schema/config.json

gui:
  # UI styling
  theme:
    inactiveBorderColor:
      - blue
    activeBorderColor:
      - cyan
      - bold
    selectedLineBgColor:
      - blue
  nerdFontsVersion: "3"
  border: single
  animateExplosion: false
  # Will have no effect until the next release
  spinner:
    frames: ["", "", "", "", "", ""]
    rate: 100
  # Messages and infos
  showRandomTip: false
  # Style my commits
  authorColors:
    "Eduard Korchmar": "#6e42d2"
  switchTabsWithPanelJumpKeys: true
# Updates are handled by the package manager
update:
  method: never
# Use console nvim for editing
os:
  editPreset: "nvim"
  editInTerminal: true
  # Edit directories with yazi
  openDirInEditor: "yazi {{dir}}"
# Ö and Ä for tabs (more accessible on German keyboards)
keybinding:
  universal:
    nextTab: "ä"
    prevTab: "ö"
# Difftastic as external diff tool
git:
  pagers:
    - externalDiffCommand: difft --color=always
# Smoother UX
notARepository: quit
disableStartupPopups: true
confirmOnQuit: false
